#!/usr/bin/env bash
#
# report.sh — Generate a Markdown vulnerability report
#

generate_report() {
    local output_dir="${1:-output}"
    local timestamp
    timestamp=$(date '+%Y-%m-%d_%H-%M-%S')
    local report_file="${output_dir}/vuln_report_${timestamp}.md"

    mkdir -p "$output_dir"

    print_section "Report Generation"

    {
        echo "# VulnTracker — Vulnerability Report"
        echo ""
        echo "**Generated:** $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "---"
        echo ""

        local vuln_count=0
        local clean_count=0

        echo "## Scan Summary"
        echo ""
        echo "| Port | Service | Version | Exploits |"
        echo "|------|---------|---------|----------|"

        for key in "${!VULN_RESULTS[@]}"; do
            local port service version
            IFS='::' read -r port _ service _ version <<< "$key"
            local exploits="${VULN_RESULTS[$key]}"

            if [[ -n "$exploits" ]]; then
                local count
                count=$(echo -n "$exploits" | grep -c '^' || true)
                echo "| ${port} | ${service} | ${version} | ${count} found |"
                ((vuln_count += count)) || true
            else
                echo "| ${port} | ${service} | ${version} | None |"
                ((clean_count++)) || true
            fi
        done

        echo ""
        echo "**Total exploits found:** ${vuln_count}"
        echo "**Services with no known exploits:** ${clean_count}"
        echo ""

        echo "---"
        echo ""
        echo "## Detailed Findings"
        echo ""

        for key in "${!VULN_RESULTS[@]}"; do
            local port service version
            IFS='::' read -r port _ service _ version <<< "$key"
            local exploits="${VULN_RESULTS[$key]}"

            echo "### ${port} — ${service} (${version})"
            echo ""

            if [[ -z "$exploits" ]]; then
                echo "No known exploits found."
                echo ""
                continue
            fi

            echo "| Exploit Title | Path |"
            echo "|---------------|------|"

            while IFS='|' read -r title path; do
                [[ -z "$title" ]] && continue
                echo "| ${title} | \`${path}\` |"
            done <<< "$exploits"

            echo ""
        done

        echo "---"
        echo ""
        echo "*Report generated by VulnTracker*"
    } > "$report_file"

    log_success "Report saved to ${BOLD}${report_file}${RESET}"
    echo "$report_file"
}
