#!/usr/bin/env bash
#
# report.sh — Generate a Markdown vulnerability report
#

generate_report() {
    local output_dir="${1:-output}"
    local timestamp
    timestamp=$(date '+%Y-%m-%d_%H-%M-%S')
    local report_file="${output_dir}/vuln_report_${timestamp}.md"

    mkdir -p "$output_dir"

    print_section "Report Generation" >&2

    {
        echo "# VulnTracker — Vulnerability Report"
        echo ""
        echo "**Generated:** $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "---"
        echo ""

        local vuln_count=0
        local clean_count=0

        echo "## Scan Summary"
        echo ""
        echo "| Port | Service | Version | Exploits |"
        echo "|------|---------|---------|----------|"

        for key in "${!VULN_RESULTS[@]}"; do
            local port service version
            IFS='::' read -r port _ service _ version <<< "$key"
            local exploits="${VULN_RESULTS[$key]}"

            if [[ -n "$exploits" ]]; then
                local count
                count=$(echo -n "$exploits" | grep -c '^' || true)
                echo "| ${port} | ${service} | ${version} | ${count} found |"
                ((vuln_count += count)) || true
            else
                echo "| ${port} | ${service} | ${version} | None |"
                ((clean_count++)) || true
            fi
        done

        echo ""
        echo "**Total exploits found:** ${vuln_count}"
        echo "**Services with no known exploits:** ${clean_count}"
        echo ""

        echo "---"
        echo ""
        echo "## Detailed Findings"
        echo ""

        for key in "${!VULN_RESULTS[@]}"; do
            local port service version
            IFS='::' read -r port _ service _ version <<< "$key"
            local exploits="${VULN_RESULTS[$key]}"

            echo "### ${port} — ${service} (${version})"
            echo ""

            if [[ -z "$exploits" ]]; then
                echo "No known exploits found."
                echo ""
                continue
            fi

            local exploit_num=0
            while IFS= read -r entry; do
                [[ -z "$entry" ]] && continue
                ((exploit_num++)) || true

                local title path details
                title=$(echo "$entry" | awk -F'\\|\\|' '{print $1}')
                path=$(echo "$entry" | awk -F'\\|\\|' '{print $2}')
                details=$(echo "$entry" | awk -F'\\|\\|' '{print $3}')

                local url codes verified filetype
                url=$(echo "$details" | awk -F';;' '{print $1}')
                codes=$(echo "$details" | awk -F';;' '{print $2}')
                verified=$(echo "$details" | awk -F';;' '{print $3}')
                filetype=$(echo "$details" | awk -F';;' '{print $4}')

                echo "#### Exploit #${exploit_num}"
                echo ""
                echo "| Field | Detail |"
                echo "|-------|--------|"
                echo "| **Exploit** | ${title} |"
                [[ -n "$url" ]] && echo "| **URL** | ${url} |"
                echo "| **Path** | \`${path}\` |"
                [[ -n "$codes" ]] && echo "| **CVE / Codes** | \`${codes}\` |"
                [[ -n "$verified" ]] && echo "| **Verified** | ${verified} |"
                [[ -n "$filetype" ]] && echo "| **File Type** | ${filetype} |"
                echo ""
            done <<< "$exploits"
        done

        echo "---"
        echo ""
        echo "*Report generated by VulnTracker*"
    } > "$report_file"

    log_success "Report saved to ${BOLD}${report_file}${RESET}" >&2
    echo "$report_file"
}
